# Generated by Django 5.2.17 on 2026-09-21 20:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of ACTIVE registrations. Must be at least 1.', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_datetime', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='event_capacity_positive', violation_error_message='Capacity must be greater than zero.'), models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='event_end_after_start', violation_error_message='End time must be after the start time.'), models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='event_title_not_empty', violation_error_message='Title cannot be blank.')],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=10)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at', '-id'],
                'indexes': [models.Index(fields=['event', 'status'], name='events_regi_event_i_c98244_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='unique_registration_per_user_event'), models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('status', 'REGISTERED')), models.Q(('cancelled_at__isnull', False), ('status', 'CANCELLED')), _connector='OR'), name='registration_status_consistent', violation_error_message='A registration is either REGISTERED (no cancellation time) or CANCELLED (with a cancellation time).')],
            },
        ),
    ]
